elearn eeclass oauth + eeclass announcement
nthumodifications/courseweb pull request #261
Opened 2024-04-02 16:25 UTC by waltsai2483

2024-04-02 20:02 UTC, ImJustChew commented
@waltsai2483 can you merge this branch with `main`.

2024-04-03 01:32 UTC, waltsai2483 commented
@ImJustChew done

2024-04-03 04:04 UTC, ImJustChew commented
Once you're done rebasing with upstream( merge with main), just leave it here and I'll review your code. Keep the pull request open.

2024-04-03 04:09 UTC, waltsai2483 commented
@ImJustChew I have done merging with main, but there's a bug that causes attachments in eeclass announcements expire and I'm fixing it
I'll notice you once it's finished

2024-04-03 04:12 UTC, ImJustChew commented
No problem, just change this PR into a draft PR.

2024-04-05 18:13 UTC, ImJustChew requested changes
Please fix the merge error, but apart from that, everything looks very good. Thanks @waltsai2483. @Joshimello will help you improve the UI. Will merge to `elearn-oauth` branch once done.

2024-04-05 18:13 UTC, ImJustChew commented on src/const/apps.ts
> -        id: 'clubs_info',
Merge Error, clubs  should be maintained

2024-04-07 07:47 UTC, merged